### ISSUE TITLE
API method error

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#226]
recover password API is in 500 error:

2023-04-28 10:10:13.577822 2023-04-28 10:10:13.577 156 DEBUG keystone.server.flask.request_processing.req_logging [req-ad9690dd-55bd-4a01-8ab1-bbb05f4cdb41 - - - - -] REQUEST_METHOD: `GET` log_request_info /usr/lib/python2.7/site-packages/keystone/server/flask/request_processing/req_logging.py:27\x1b[00m
2023-04-28 10:10:13.578002 2023-04-28 10:10:13.577 156 DEBUG keystone.server.flask.request_processing.req_logging [req-ad9690dd-55bd-4a01-8ab1-bbb05f4cdb41 - - - - -] SCRIPT_NAME: `` log_request_info /usr/lib/python2.7/site-packages/keystone/server/flask/request_processing/req_logging.py:28\x1b[00m
2023-04-28 10:10:13.578165 2023-04-28 10:10:13.578 156 DEBUG keystone.server.flask.request_processing.req_logging [req-ad9690dd-55bd-4a01-8ab1-bbb05f4cdb41 - - - - -] PATH_INFO: `/v3/users/35d3c51f389b4e078d7e7d8f5190fc1a/recover_password` log_request_info /usr/lib/python2.7/site-packages/keystone/server/flask/request_processing/req_logging.py:29\x1b[00m
2023-04-28 10:10:13.578463 2023-04-28 10:10:13.578 156 ERROR keystone.api.spassword [req-ad9690dd-55bd-4a01-8ab1-bbb05f4cdb41 - - - - -] SPassword was not configured or enabled\x1b[00m
2023-04-28 10:10:13.583284 mod_wsgi (pid=156): Exception occurred processing WSGI script '/usr/bin/keystone-wsgi-public'.
2023-04-28 10:10:13.583296 Traceback (most recent call last):
2023-04-28 10:10:13.583302   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
2023-04-28 10:10:13.593276     return self.wsgi_app(environ, start_response)
2023-04-28 10:10:13.593284   File "/usr/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
2023-04-28 10:10:13.593449     return self.app(environ, start_response)
2023-04-28 10:10:13.593454   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2023-04-28 10:10:13.593608     resp = self.call_func(req, *args, **kw)
2023-04-28 10:10:13.593612   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2023-04-28 10:10:13.593620     return self.func(req, *args, **kwargs)
2023-04-28 10:10:13.593622   File "/usr/lib/python2.7/site-packages/oslo_middleware/debug.py", line 40, in __call__
2023-04-28 10:10:13.593726     resp = req.get_response(self.application)
2023-04-28 10:10:13.593732   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2023-04-28 10:10:13.594264     application, catch_exc_info=False)
2023-04-28 10:10:13.594267   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2023-04-28 10:10:13.594275     app_iter = application(self.environ, start_response)
2023-04-28 10:10:13.594279   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2023-04-28 10:10:13.594285     resp = self.call_func(req, *args, **kw)
2023-04-28 10:10:13.594288   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2023-04-28 10:10:13.594293     return self.func(req, *args, **kwargs)
2023-04-28 10:10:13.594295   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
2023-04-28 10:10:13.594417     response = req.get_response(self.application)
2023-04-28 10:10:13.594420   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2023-04-28 10:10:13.594426     application, catch_exc_info=False)
2023-04-28 10:10:13.594429   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2023-04-28 10:10:13.594434     app_iter = application(self.environ, start_response)
2023-04-28 10:10:13.594437   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 143, in __call__
2023-04-28 10:10:13.594442     return resp(environ, start_response)
2023-04-28 10:10:13.594444   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2023-04-28 10:10:13.594448     resp = self.call_func(req, *args, **kw)
2023-04-28 10:10:13.594451   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2023-04-28 10:10:13.594455     return self.func(req, *args, **kwargs)
2023-04-28 10:10:13.594459   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
2023-04-28 10:10:13.594463     response = req.get_response(self.application)
2023-04-28 10:10:13.594465   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2023-04-28 10:10:13.594470     application, catch_exc_info=False)
2023-04-28 10:10:13.594472   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2023-04-28 10:10:13.594477     app_iter = application(self.environ, start_response)
2023-04-28 10:10:13.594479   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2023-04-28 10:10:13.594483     resp = self.call_func(req, *args, **kw)
2023-04-28 10:10:13.594486   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2023-04-28 10:10:13.594489     return self.func(req, *args, **kwargs)
2023-04-28 10:10:13.594492   File "/usr/lib/python2.7/site-packages/osprofiler/web.py", line 112, in __call__
2023-04-28 10:10:13.594618     return request.get_response(self.application)
2023-04-28 10:10:13.594621   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2023-04-28 10:10:13.594625     application, catch_exc_info=False)
2023-04-28 10:10:13.594629   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2023-04-28 10:10:13.594635     app_iter = application(self.environ, start_response)
2023-04-28 10:10:13.594637   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2023-04-28 10:10:13.594641     resp = self.call_func(req, *args, **kw)
2023-04-28 10:10:13.594643   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2023-04-28 10:10:13.594647     return self.func(req, *args, **kwargs)
2023-04-28 10:10:13.594650   File "/usr/lib/python2.7/site-packages/oslo_middleware/request_id.py", line 58, in __call__
2023-04-28 10:10:13.594751     response = req.get_response(self.application)
2023-04-28 10:10:13.594754   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2023-04-28 10:10:13.594760     application, catch_exc_info=False)
2023-04-28 10:10:13.594764   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2023-04-28 10:10:13.594770     app_iter = application(self.environ, start_response)
2023-04-28 10:10:13.594773   File "/usr/lib/python2.7/site-packages/keystone/server/flask/request_processing/middleware/url_normalize.py", line 38, in __call__
2023-04-28 10:10:13.594802     return self.app(environ, start_response)
2023-04-28 10:10:13.594804   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2023-04-28 10:10:13.594808     resp = self.call_func(req, *args, **kw)
2023-04-28 10:10:13.594810   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2023-04-28 10:10:13.594814     return self.func(req, *args, **kwargs)
2023-04-28 10:10:13.594817   File "/usr/lib/python2.7/site-packages/keystonemiddleware/auth_token/__init__.py", line 333, in __call__
2023-04-28 10:10:13.595260     response = req.get_response(self._app)
2023-04-28 10:10:13.595277   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2023-04-28 10:10:13.595309     application, catch_exc_info=False)
2023-04-28 10:10:13.595317   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2023-04-28 10:10:13.595334     app_iter = application(self.environ, start_response)
2023-04-28 10:10:13.595342   File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 826, in __call__
2023-04-28 10:10:13.595877     return app(environ, start_response)
2023-04-28 10:10:13.595887   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
2023-04-28 10:10:13.595907     response = self.handle_exception(e)
2023-04-28 10:10:13.595916   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596260     return original_handler(e)
2023-04-28 10:10:13.596268   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596286     return original_handler(e)
2023-04-28 10:10:13.596292   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596305     return original_handler(e)
2023-04-28 10:10:13.596312   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596334     return original_handler(e)
2023-04-28 10:10:13.596340   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596353     return original_handler(e)
2023-04-28 10:10:13.596359   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596371     return original_handler(e)
2023-04-28 10:10:13.596376   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596388     return original_handler(e)
2023-04-28 10:10:13.596393   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596405     return original_handler(e)
2023-04-28 10:10:13.596410   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596421     return original_handler(e)
2023-04-28 10:10:13.596428   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596439     return original_handler(e)
2023-04-28 10:10:13.596445   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596457     return original_handler(e)
2023-04-28 10:10:13.596462   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596473     return original_handler(e)
2023-04-28 10:10:13.596479   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596490     return original_handler(e)
2023-04-28 10:10:13.596497   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596508     return original_handler(e)
2023-04-28 10:10:13.596514   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596525     return original_handler(e)
2023-04-28 10:10:13.596531   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596543     return original_handler(e)
2023-04-28 10:10:13.596548   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596560     return original_handler(e)
2023-04-28 10:10:13.596566   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596577     return original_handler(e)
2023-04-28 10:10:13.596583   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596594     return original_handler(e)
2023-04-28 10:10:13.596600   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596612     return original_handler(e)
2023-04-28 10:10:13.596617   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596628     return original_handler(e)
2023-04-28 10:10:13.596634   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596646     return original_handler(e)
2023-04-28 10:10:13.596651   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596662     return original_handler(e)
2023-04-28 10:10:13.596668   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596681     return original_handler(e)
2023-04-28 10:10:13.596687   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596699     return original_handler(e)
2023-04-28 10:10:13.596704   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596716     return original_handler(e)
2023-04-28 10:10:13.596723   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596735     return original_handler(e)
2023-04-28 10:10:13.596740   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596754     return original_handler(e)
2023-04-28 10:10:13.596760   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596771     return original_handler(e)
2023-04-28 10:10:13.596777   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596788     return original_handler(e)
2023-04-28 10:10:13.596794   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596805     return original_handler(e)
2023-04-28 10:10:13.596811   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2023-04-28 10:10:13.596823     return original_handler(e)
2023-04-28 10:10:13.596833   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
2023-04-28 10:10:13.596847     reraise(exc_type, exc_value, tb)
2023-04-28 10:10:13.596853   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
2023-04-28 10:10:13.596865     return self.handle_error(e)
2023-04-28 10:10:13.596871   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
2023-04-28 10:10:13.596883     response = self.full_dispatch_request()
2023-04-28 10:10:13.596889   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
2023-04-28 10:10:13.596901     return self.finalize_request(rv)
2023-04-28 10:10:13.596907   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1833, in finalize_request
2023-04-28 10:10:13.596919     response = self.process_response(response)
2023-04-28 10:10:13.596925   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2112, in process_response
2023-04-28 10:10:13.596938     response = handler(response)
2023-04-28 10:10:13.596946   File "/usr/lib/python2.7/site-packages/keystone/server/flask/common.py", line 153, in _assert_rbac_enforcement_called
2023-04-28 10:10:13.597199     g, enforcer._ENFORCEMENT_CHECK_ATTR, False), msg  # nosec
2023-04-28 10:10:13.597218 AssertionError: PROGRAMMING ERROR: enforcement (`keystone.common.rbac_enforcer.enforcer.RBACKEnforcer.enforce_call()`) has not been called; API is unenforced.
172.17.0.1 - - [28/Apr/2023:10:10:13 +0000] "GET /v3/users/35d3c51f389b4e078d7e7d8f5190fc1a/recover_password HTTP/1.1" 500 527 "-" "curl/7.88.1"

**Comment by AlvaroVega** [comment]
This just happends when SNDFA is not configured.
To fix it, then configure 
  - SPASSWORD_SNDFA=True
