### ISSUE TITLE
POST request causes HTTP error 500

### ISSUE THREAD

**Issue by rg2011** [telefonicaid/fiware-keystone-spassword#242]
The following POST request causes keystone to abort with an HTTP error 500:

```
curl -v -X POST -H 'Content-Type:' http://<keystone URL>:5001/xmlrpc.php -d '{}'
```

Tested with keystone 1.17.0.

This is the error trace:

```
2024-10-29 07:44:03.123028 mod_wsgi (pid=152): Exception occurred processing WSGI script '/usr/bin/keystone-wsgi-public'.
2024-10-29 07:44:03.128893 Traceback (most recent call last):
2024-10-29 07:44:03.129153   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
2024-10-29 07:44:03.143165     return self.wsgi_app(environ, start_response)
2024-10-29 07:44:03.143257   File "/usr/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
2024-10-29 07:44:03.149158     return self.app(environ, start_response)
2024-10-29 07:44:03.149217   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2024-10-29 07:44:03.154764     resp = self.call_func(req, *args, **kw)
2024-10-29 07:44:03.154827   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2024-10-29 07:44:03.154886     return self.func(req, *args, **kwargs)
2024-10-29 07:44:03.154904   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
2024-10-29 07:44:03.159802     response = req.get_response(self.application)
2024-10-29 07:44:03.160562   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2024-10-29 07:44:03.162774     application, catch_exc_info=False)
2024-10-29 07:44:03.162830   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2024-10-29 07:44:03.162892     app_iter = application(self.environ, start_response)
2024-10-29 07:44:03.162917   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 143, in __call__
2024-10-29 07:44:03.162968     return resp(environ, start_response)
2024-10-29 07:44:03.162997   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2024-10-29 07:44:03.163029     resp = self.call_func(req, *args, **kw)
2024-10-29 07:44:03.163057   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2024-10-29 07:44:03.163103     return self.func(req, *args, **kwargs)
2024-10-29 07:44:03.163117   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
2024-10-29 07:44:03.163148     response = req.get_response(self.application)
2024-10-29 07:44:03.163162   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2024-10-29 07:44:03.163191     application, catch_exc_info=False)
2024-10-29 07:44:03.163219   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2024-10-29 07:44:03.163264     app_iter = application(self.environ, start_response)
2024-10-29 07:44:03.163291   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2024-10-29 07:44:03.163322     resp = self.call_func(req, *args, **kw)
2024-10-29 07:44:03.163349   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2024-10-29 07:44:03.163380     return self.func(req, *args, **kwargs)
2024-10-29 07:44:03.163408   File "/usr/lib/python2.7/site-packages/osprofiler/web.py", line 112, in __call__
2024-10-29 07:44:03.166304     return request.get_response(self.application)
2024-10-29 07:44:03.166347   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2024-10-29 07:44:03.166389     application, catch_exc_info=False)
2024-10-29 07:44:03.166417   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2024-10-29 07:44:03.166447     app_iter = application(self.environ, start_response)
2024-10-29 07:44:03.166469   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2024-10-29 07:44:03.166496     resp = self.call_func(req, *args, **kw)
2024-10-29 07:44:03.166524   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2024-10-29 07:44:03.166552     return self.func(req, *args, **kwargs)
2024-10-29 07:44:03.166579   File "/usr/lib/python2.7/site-packages/oslo_middleware/request_id.py", line 58, in __call__
2024-10-29 07:44:03.167222     response = req.get_response(self.application)
2024-10-29 07:44:03.167259   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2024-10-29 07:44:03.167300     application, catch_exc_info=False)
2024-10-29 07:44:03.167326   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2024-10-29 07:44:03.167355     app_iter = application(self.environ, start_response)
2024-10-29 07:44:03.167495   File "/usr/lib/python2.7/site-packages/keystone/server/flask/request_processing/middleware/url_normalize.py", line 38, in __call__
2024-10-29 07:44:03.175957     return self.app(environ, start_response)
2024-10-29 07:44:03.176013   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 129, in __call__
2024-10-29 07:44:03.176068     resp = self.call_func(req, *args, **kw)
2024-10-29 07:44:03.176102   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 193, in call_func
2024-10-29 07:44:03.176138     return self.func(req, *args, **kwargs)
2024-10-29 07:44:03.176397   File "/usr/lib/python2.7/site-packages/keystonemiddleware/auth_token/__init__.py", line 333, in __call__
2024-10-29 07:44:03.181737     response = req.get_response(self._app)
2024-10-29 07:44:03.181766   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1314, in send
2024-10-29 07:44:03.181794     application, catch_exc_info=False)
2024-10-29 07:44:03.181800   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1278, in call_application
2024-10-29 07:44:03.181812     app_iter = application(self.environ, start_response)
2024-10-29 07:44:03.181818   File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 826, in __call__
2024-10-29 07:44:03.184641     return app(environ, start_response)
2024-10-29 07:44:03.184671   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
2024-10-29 07:44:03.184740     response = self.handle_exception(e)
2024-10-29 07:44:03.184772   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187736     return original_handler(e)
2024-10-29 07:44:03.187775   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187806     return original_handler(e)
2024-10-29 07:44:03.187813   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187828     return original_handler(e)
2024-10-29 07:44:03.187834   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187847     return original_handler(e)
2024-10-29 07:44:03.187853   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187866     return original_handler(e)
2024-10-29 07:44:03.187872   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187884     return original_handler(e)
2024-10-29 07:44:03.187890   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187903     return original_handler(e)
2024-10-29 07:44:03.187909   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187922     return original_handler(e)
2024-10-29 07:44:03.187928   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187941     return original_handler(e)
2024-10-29 07:44:03.187946   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187959     return original_handler(e)
2024-10-29 07:44:03.187964   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187977     return original_handler(e)
2024-10-29 07:44:03.187982   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.187995     return original_handler(e)
2024-10-29 07:44:03.188001   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188014     return original_handler(e)
2024-10-29 07:44:03.188019   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188032     return original_handler(e)
2024-10-29 07:44:03.188037   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188050     return original_handler(e)
2024-10-29 07:44:03.188056   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188069     return original_handler(e)
2024-10-29 07:44:03.188074   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188087     return original_handler(e)
2024-10-29 07:44:03.188092   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188105     return original_handler(e)
2024-10-29 07:44:03.188110   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188123     return original_handler(e)
2024-10-29 07:44:03.188129   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188176     return original_handler(e)
2024-10-29 07:44:03.188184   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188197     return original_handler(e)
2024-10-29 07:44:03.188203   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188216     return original_handler(e)
2024-10-29 07:44:03.188221   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188234     return original_handler(e)
2024-10-29 07:44:03.188240   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188252     return original_handler(e)
2024-10-29 07:44:03.188258   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188270     return original_handler(e)
2024-10-29 07:44:03.188276   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188288     return original_handler(e)
2024-10-29 07:44:03.188294   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188307     return original_handler(e)
2024-10-29 07:44:03.188312   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188325     return original_handler(e)
2024-10-29 07:44:03.188330   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188344     return original_handler(e)
2024-10-29 07:44:03.188349   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188362     return original_handler(e)
2024-10-29 07:44:03.188367   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188380     return original_handler(e)
2024-10-29 07:44:03.188385   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188398     return original_handler(e)
2024-10-29 07:44:03.188420   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
2024-10-29 07:44:03.188438     reraise(exc_type, exc_value, tb)
2024-10-29 07:44:03.188445   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
2024-10-29 07:44:03.188459     response = self.full_dispatch_request()
2024-10-29 07:44:03.188466   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
2024-10-29 07:44:03.188479     rv = self.handle_user_exception(e)
2024-10-29 07:44:03.188485   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188498     return original_handler(e)
2024-10-29 07:44:03.188504   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188516     return original_handler(e)
2024-10-29 07:44:03.188522   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188534     return original_handler(e)
2024-10-29 07:44:03.188540   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188553     return original_handler(e)
2024-10-29 07:44:03.188558   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188571     return original_handler(e)
2024-10-29 07:44:03.188577   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188590     return original_handler(e)
2024-10-29 07:44:03.188596   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188609     return original_handler(e)
2024-10-29 07:44:03.188614   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188627     return original_handler(e)
2024-10-29 07:44:03.188633   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188645     return original_handler(e)
2024-10-29 07:44:03.188651   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188664     return original_handler(e)
2024-10-29 07:44:03.188669   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188682     return original_handler(e)
2024-10-29 07:44:03.188687   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188700     return original_handler(e)
2024-10-29 07:44:03.188706   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188718     return original_handler(e)
2024-10-29 07:44:03.188724   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188737     return original_handler(e)
2024-10-29 07:44:03.188742   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188755     return original_handler(e)
2024-10-29 07:44:03.188761   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188773     return original_handler(e)
2024-10-29 07:44:03.188779   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188792     return original_handler(e)
2024-10-29 07:44:03.188797   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188810     return original_handler(e)
2024-10-29 07:44:03.188816   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188829     return original_handler(e)
2024-10-29 07:44:03.188834   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188847     return original_handler(e)
2024-10-29 07:44:03.188853   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188865     return original_handler(e)
2024-10-29 07:44:03.188871   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188884     return original_handler(e)
2024-10-29 07:44:03.188889   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188902     return original_handler(e)
2024-10-29 07:44:03.188907   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188920     return original_handler(e)
2024-10-29 07:44:03.188926   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188938     return original_handler(e)
2024-10-29 07:44:03.188945   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188958     return original_handler(e)
2024-10-29 07:44:03.188964   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188976     return original_handler(e)
2024-10-29 07:44:03.188982   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.188994     return original_handler(e)
2024-10-29 07:44:03.189000   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.189013     return original_handler(e)
2024-10-29 07:44:03.189018   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.189031     return original_handler(e)
2024-10-29 07:44:03.189037   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.189049     return original_handler(e)
2024-10-29 07:44:03.189055   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
2024-10-29 07:44:03.189068     return original_handler(e)
2024-10-29 07:44:03.189074   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
2024-10-29 07:44:03.189088     reraise(exc_type, exc_value, tb)
2024-10-29 07:44:03.189093   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
2024-10-29 07:44:03.189107     rv = self.preprocess_request()
2024-10-29 07:44:03.189113   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2087, in preprocess_request
2024-10-29 07:44:03.189127     rv = func()
2024-10-29 07:44:03.189137   File "/usr/lib/python2.7/site-packages/keystone/server/flask/request_processing/json_body.py", line 41, in json_body_before_request
2024-10-29 07:44:03.189699     or flask.request.headers['Content-Type'] == ''):
2024-10-29 07:44:03.189920   File "/usr/lib/python2.7/site-packages/werkzeug/datastructures.py", line 1353, in __getitem__
2024-10-29 07:44:03.193972     return _unicodify_header_value(self.environ[key])
2024-10-29 07:44:03.195481 KeyError: 'CONTENT_TYPE'
92.177.14.122 - - [29/Oct/2024:07:44:03 +0000] "POST /xmlrpc.php HTTP/1.1" 500 527 "-" "curl/7.81.0"
```

**Comment by AlvaroVega** [comment]
With my current 1.18 keystone:

```
curl -v -X POST -H 'Content-Type:' http://localhost:5001/xmlrpc.php -d '{}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:5001...
* Connected to localhost (127.0.0.1) port 5001 (#0)
> POST /xmlrpc.php HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Length: 2
> 
< HTTP/1.1 404 NOT FOUND
< Date: Tue, 29 Oct 2024 08:15:21 GMT
< Server: Apache/2.4.57 (CentOS Stream) mod_wsgi/4.7.1 Python/3.9
< Content-Length: 207
< Vary: X-Auth-Token
< x-openstack-request-id: req-5fdfd604-de31-46e8-b8d0-a6eb1e18c4f0
< Content-Type: text/html; charset=utf-8
< 
<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
* Connection #0 to host localhost left intact
```

**Comment by AlvaroVega** [comment]
Against keystone 1.17.0 full curl report is:

``
*   Trying MM.NN.OO.PP:5001...
* Connected to ANOTHER (MM.NN.OO.PP) port 5001 (#0)
> POST /xmlrpc.php HTTP/1.1
> Host: ANOTHER:5001
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Length: 2
> 
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 29 Oct 2024 08:17:23 GMT
< Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5
< Content-Length: 527
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
* Closing connection 0
``
It seems that **mod_wsgi/3.4** from keystone **stein** is the responsible of that error
